### ISSUE TITLE
Bug in odata2/sqlds.py

### ISSUE THREAD

**Issue by chebizarro** [swl10/pyslet#12]
Hi,

First off, thanks for the fantastic library, I've been enjoying using it immensely!
In the process of setting up an odata2 server with a Postgres back end, I came across a bug in sqlds.py and an omission in the library itself.

In terms of the bug, when developing an Postgres SQLContainer class, I noticed I was getting a NotImplementedError thrown from the SQLParams class. On investigating further, I saw that the postgres db2 api implementation I am using (psycopg2) returns a paramstyle of pyformat. In looking at the constructor for the SQLEntityContainer class I saw that it only implements qmark, numeric and named. As there was no SQLParam sub class for pyformat I tried setting it to qmark, numeric and then named. The first of these was incompatible with Postgres but the second and third threw a Python error which I believe is caused by the incorrect class name (QMarkParams) being used in the numeric and named SQLParam class constructors to call its super constructor. Eg:

```
class NumericParams(SQLParams):

    def __init__(self):
            super(QMarkParams, self).__init__()
            self.params = []
```

and

```
class NamedParams(SQLParams):

    def __init__(self):
            super(QMarkParams, self).__init__()
            self.params = []
```

Should these classes not be calling themselves in the super function?

In any case, since none of these paramstyles were compatible with Postgres, I rolled my own for  pyformatparams and set the paramstyles property in the Postgres SQLEntityContainer subclass. This now works perfectly fine:

If you are at all interested, I can submit a pull request with the above fixes and the pyformatparams class. I have a working Postgres SQLEntityContainer but it hasn't been fully tested yet but would be only too happy to include that as well.

In working out a solution to all of this, I noticed that the [db api documentation](http://legacy.python.org/dev/peps/pep-0249/#paramstyle) specifies 5 styles:

| paramstyle | Meaning |
| --- | --- |
| qmark | Question mark style, e.g. ...WHERE name=? |
| numeric | Numeric, positional style, e.g. ...WHERE name=:1 |
| named | Named style, e.g. ...WHERE name=:name |
| format | ANSI C printf format codes, e.g. ...WHERE name=%s |
| pyformat | Python extended format codes, e.g. ...WHERE name=%(name)s |

qmark, numeric and named are defined in sqlds.py, I have rolled my own pyformat which just leaves format. I can take a crack at this if you like - it's up to you.

Once again, many thanks for this elegant piece of software, it is greatly appreciated.

**Comment by swl10** [comment]
Python 3 requires moving from MySQLdb to PyMySQL which uses pyformat!  Re-opening.
