### ISSUE TITLE
Possible bug in parsing AssociationSet names

### ISSUE THREAD

**Issue by chebizarro** [swl10/pyslet#18]
Hi again,
I am attempting to parse a rather large [metadata file](https://sfsfbizxtrial.hana.ondemand.com/odata/v2/$metadata) (2.4Mb) from SAP and the parser keeps choking when attempting to declare an AssociationSet in the EntityContainer namespace.

I should state at the outset that I am unable to independently verify that the metadata being returned is valid, but I would assume that it is, coming from the SAP HANA service. I would put a copy of the file online but I'm not sure if that would be violating the terms and conditions of the service agreement. It's free to register if you're so inclined.

The error the parser throws is a [DuplicateName error](https://github.com/swl10/pyslet/blob/master/pyslet/odata2/csdl.py#L458) and the AssociationSet that it throws this error on has the associationName attribute of "SFOData.Background_Picklist-One_AddressType_picklist" 

Inspecting the code in pudb, I saw that this was happening because the [RegEx  expression](https://github.com/swl10/pyslet/blob/master/pyslet/odata2/csdl.py#L47) in csdl.py excludes the dash character by only looking for "Pc". This causes the entity's name to be left as "Default" and the above error to be thrown.

AFAIK, the dash is a legal character in entity names, but I could be wrong. I'm trying to find a reference but RFCs make my head hurt.

In any case, I amended the RegEx to include "Pd" and it continues parsing until... it throws a [ModelIncomplete](https://github.com/swl10/pyslet/blob/master/pyslet/odata2/csdl.py#L4299) error. 

This is about as far as I have gotten before my eyes starting bleeding. I will look into it further and add to the above.

**Comment by swl10** [comment]
I note that OData v4 contains some provisions to help people who are modelling this type of schema.  Given the age of this issue I'm closing this one now as I don't see this being fully resolved in the OData v2 stack.
