### ISSUE TITLE
PEP-8 Compliance

### ISSUE THREAD

**Issue by swl10** [swl10/pyslet#3]
$ pep8 --count -qq pyslet
77649

$ pep8 --statistics -qq pyslet
376     E101 indentation contains mixed spaces and tabs
4       E112 expected an indented block
2       E113 unexpected indentation
8       E122 continuation line missing indentation or outdented
1       E126 continuation line over-indented for hanging indent
112     E128 continuation line under-indented for visual indent
5       E201 whitespace after '['
10      E202 whitespace before ']'
96      E211 whitespace before '('
16      E223 tab before operator
11619   E225 missing whitespace around operator
2       E227 missing whitespace around bitwise or shift operator
1023    E228 missing whitespace around modulo operator
11168   E231 missing whitespace after ','
142     E261 at least two spaces before inline comment
390     E262 inline comment should start with '# '
116     E265 block comment should start with '# '
2       E271 multiple spaces after keyword
1       E272 multiple spaces before keyword
4       E273 tab after keyword
369     E302 expected 2 blank lines, found 1
25      E303 too many blank lines (5)
41      E401 multiple imports on one line
1834    E501 line too long (94 > 79 characters)
303     E701 multiple statements on one line (colon)
25      E702 multiple statements on one line (semicolon)
1       E703 statement ends with a semicolon
7       E712 comparison to False should be 'if cond is False:' or 'if not cond:'
10      E713 test for membership should be 'not in'
5       E714 test for object identity should be 'is not'
5       E721 do not compare types, use 'isinstance()'
45198   W191 indentation contains tabs
802     W291 trailing whitespace
1       W292 no newline at end of file
3908    W293 blank line contains whitespace
18      W391 blank line at end of file

Thanks to @sassman for the suggestion; I will work on getting these numbers down.

**Comment by anna-liao** [comment]
@swl10 I would like to work on this issue.  Any guidance?

**Comment by swl10** [comment]
@anna-liao thanks for your offer and the pull request.  I couldn't find your original comment on GitHub to reply, sorry.  I will look to integrate these into master shortly.

For info, the approach I originally took was to add a pep8s build target to the Makefile.  So "make pep8s" runs a small script that updates pep8-count.txt with current progress and prints the stats to stdout.  The summary statistic today is which agrees with your 800+ figure:

Mon 31 Oct 2016 08:24:02 GMT
881
 
The current version of this file indicates that I haven't run it for some time - that's because I extended the approach to include flake8 output too.  So looking in flake8-count.txt shows a better history of progress towards compliance.

Because flake8 is more demanding I've been working on a file-by-file basis, including using decorators (defined in pyslet's own pep8 module - see docs for details) to enable improved method naming while retaining backwards compatibility.  To further complicate matters I tend to tackle Python 3 compatibility at the same time.  Each time the changes to a file are complete I add its name to pep8-done.txt.  Before committing changes I run pep8-regression.py to check for regression issues making it easier to keep the code clean.

Of course, the flake8 approach is slower and it makes sense to fix the simpler pep8 issues separately as per your pull request.  Although I do run "autopep8 -i -r pyslet" as part of the flake8 build target I'm still using version 1.0.4 and I see that things have moved on.  Also that doesn't touch the unittests which are often the worst offenders for long lines and general readability.

Anyway, thanks again for your interest and the time you've invested in helping.  I'll switch to your branch and merge changes shortly.  One question, excuse my ignorance but what is purpose of the travis.txt file in your first commit?

**Comment by anna-liao** [comment]
@swl10 Thanks for the detailed info.  Shall I work with flake8 and upgrading to Python 3 compatibility?  This pull request is preparation work for development of a module to serialise the Wikimedia quiz format with @jayvdb and @mvolz.

Oh, sorry about the travis.txt.  I am new to using Travis CI, and wanted to trigger the CI test to run on the forked version before my modifications.  I was meaning to delete that file.

**Comment by mvolz** [comment]
@anna-liao If you want to stop tracking a file in git, you can do ```git rm --cached travis.txt``` and then do a new commit. (or ```git commit --amend``` to amend it) and then push the changes to your branch. This will leave the file but remove it from the git index. 

You can also add files you don't want to add to a git repository, you can add them to your .gitignore file: https://help.github.com/articles/ignoring-files/ (forgive me if you already know this :D)

**Comment by mvolz** [comment]
Although perhaps better to leave it in, so that the tests get triggered in this library? @swl10

**Comment by anna-liao** [comment]
oh, I don't think the travis.txt is necessary to trigger the CI tests.
Later, I found in a google search, there is a way to push an empty commit
to trigger the CI tests.  I have removed the file and pushed a commit.

**Comment by swl10** [comment]
@anna-liao @mvolz I've set Travis to build pull requests automatically (default config) so I don't think you need to do anything special.

Your commits have spurred me on to close out some of the outstanding issues in the IMS QTI modules that were blocking a shift to Python 3.  It wasn't quite automatic as I still had a few classes waiting to be shifted into the sub-packages.  Anyway, it's done now and the tests are passing in Python 3 for the QTI/CP and metadata modules too.

There are only a handful of modules left with flake8 issues in now and they may not be useful for your project anyway - unless you are using the IMS common cartridge formats.  I may try and close these out over the next few days so that you can get going with something more substantive.
