### ISSUE TITLE
Safe URL's with $value

### ISSUE THREAD

**Issue by stevehof** [swl10/pyslet#42]
I've noticed that the $ in the src URI's that are generated should probably be encoded. I've looked into replacing the $ with %24's but the ODataURI looks for the $value when constructing and removes it from the navPath. 

I'd push my solution, but there seem to be a few simple solutions, you might prefer one over the other.

This generally isn't an issue in the modern browser or consumer, however $value was removed when testing with 'wget'. I think bash in ubuntu thought it was a var. This just highlighted the fact it wasn't encoded.

**Comment by swl10** [comment]
The '$' in Entities(key)/$value is in a path segment rather than the query string so it doesn't have to be escaped (though it would be benign).  Is it causing a problem?

**Comment by stevehof** [comment]
Just with wget in linux (because of the $ making it think it's a variable), not with browsers and i haven't tested with... Was just wondering on the standard :)
