### ISSUE TITLE
"Docs" link in Read the docs leads to Jupyter Documentation

### ISSUE THREAD

**Issue by alonisser** [swl10/pyslet#45]
go to pyslet [read the docs site](http://pyslet.readthedocs.org/en/latest/odatav2_client.html)

Press on "pyslet" header or "docs" . both lead to url: http://pyslet.readthedocs.org/en/latest/index.html

expected: some general pyslet docs

Actual: a somewhat broken Jupyter Documentation site

**Comment by swl10** [comment]
I am unable to reproduce this issue.  It may have been a transient problem with readthedocs DNS I guess, the links all appear to be going to right place.  Is it still an issue for you?

**Comment by alonisser** [comment]
looks ok now. :)
