### ISSUE TITLE
authentication example in docs

### ISSUE THREAD

**Issue by allox** [swl10/pyslet#60]
The authentication is missing the documentation
http://pyslet.readthedocs.io/en/latest/http/auth.html

So, how to enable (basic) authentication? 

(I know there is a blogpost about it, but it seems to be incomplete and gives many errors)

**Comment by swl10** [comment]
Thanks for spotting these issues with the docs.  For now, you can find an example of a client that uses basic auth in samples/scihub.copernicus.eu/download.py

Does that help, or are you implementing an auth-protected server?

**Comment by salimrahal** [comment]
Hello, I didnt find the samples? could you post a code snippet here plz?

**Comment by swl10** [comment]
I've added some content to the above [documentation page](http://pyslet.readthedocs.io/en/latest/http/auth.html) which should help get you going.

There is a code snippet in [this source file](https://github.com/swl10/pyslet/blob/master/samples/scihub.copernicus.eu/download.py)

Does that help?

**Comment by salimrahal** [comment]
Thank you, yes it helps
